version: '3.3'

services:
  web:
    build: ./services/web
    volumes:
      - ./services/web/app:/home/app/app
      - ./services/web/migrations:/home/app/migrations
      - ./services/web/config.py:/home/app/config.py
      - ./services/web/main.py:/home/app/main.py
      - ./services/web/boot.dev.sh:/home/app/boot.dev.sh
    ports:
      - 80:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER=data_monster
      - POSTGRES_PASSWORD=data_monster
      - POSTGRES_DB=app_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
