version: '3.3'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    volumes:
      - ./services/web/app:/home/app/app
      - ./services/web/migrations:/home/app/migrations
      - ./services/web/config.py:/home/app/config.py
      - ./services/web/main.py:/home/app/main.py
      - ./services/web/boot.prod.sh:/home/app/boot.prod.sh
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data_prod:
