"""Add new field for user table

Revision ID: 0369fb0428f6
Revises: 0b55982c7242
Create Date: 2020-03-01 12:47:53.301624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0369fb0428f6'
down_revision = '0b55982c7242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('middle_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('second_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('send_flag', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('vector', sa.Text(), nullable=True))
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'])
    op.create_index(op.f('ix_user_middle_name'), 'user', ['middle_name'])
    op.create_index(op.f('ix_user_second_name'), 'user', ['second_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_second_name'), table_name='user')
    op.drop_index(op.f('ix_user_middle_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_column('user', 'vector')
    op.drop_column('user', 'send_flag')
    op.drop_column('user', 'second_name')
    op.drop_column('user', 'middle_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
