"""Add avatar for User table

Revision ID: 057d8f27567b
Revises: 472cf2395c02
Create Date: 2020-06-04 15:12:01.200475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057d8f27567b'
down_revision = '472cf2395c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
