"""Add init data users and roles

Revision ID: 0b55982c7242
Revises: 5282b715694a
Create Date: 2020-02-27 22:25:34.327474

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0b55982c7242'
down_revision = '5282b715694a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user = sa.sql.table(
        'user',
        sa.Column('id', sa.Integer),
        sa.Column('username', sa.String(64)),
        sa.Column('email', sa.String(120)),
        sa.Column('password_hash', sa.String(128))
    )

    role = sa.sql.table(
        'role',
        sa.Column('id', sa.Integer()),
        sa.Column('name', sa.String(length=50)),
    )

    user_role = sa.sql.table(
        'user_role',
        sa.Column('id', sa.Integer()),
        sa.Column('user_id', sa.Integer()),
        sa.Column('role_id', sa.Integer()),
    )

    op.bulk_insert(
        user,
        [
            {
                'email': 'admin@mail.com',
                'password_hash': 'pbkdf2:sha256:150000$LmL92VQR$f5a30d0d01616ee7a0163a162c7415c8b6afdcbd155d7626f7520b8f9c6552e2'
            }
        ]
    )

    op.bulk_insert(
        role,
        [
            {'name': 'ROLE_ADMIN'},
            {'name': 'ROLE_SECRETARY'},
            {'name': 'ROLE_EMPLOYEE'},
        ]
    )

    op.bulk_insert(
        user_role,
        [
            {'user_id': 1, 'role_id': 1}
        ]
    )

    # op.execute('''
    #     SELECT setval('user_id_seq', (SELECT max("id") from "user"));
    #     SELECT setval('role_id_seq', (SELECT max("id") from "role"));
    #     SELECT setval('user_role_id_seq', (SELECT max("id") from "user_role"));
    # ''')
    # ### end Alembic commands ###


def downgrade():
    pass
