"""Add camera table

Revision ID: 472cf2395c02
Revises: 9e48a366040f
Create Date: 2020-03-22 07:33:07.721761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472cf2395c02'
down_revision = '9e48a366040f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera')
    # ### end Alembic commands ###
