"""Add new fiekd Event table

Revision ID: 69f80272ac41
Revises: 057d8f27567b
Create Date: 2020-06-05 10:49:55.558328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f80272ac41'
down_revision = '057d8f27567b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('context', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'context')
    # ### end Alembic commands ###
